version: 2

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: k8s-manifest-diff
    main: ./cmd/k8s-manifest-diff
    binary: k8s-manifest-diff
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser

archives:
  - id: k8s-manifest-diff
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - '^refactor:'
      - '^style:'
      - '^Merge pull request'
  groups:
    - title: 'Features'
      regexp: '^feat'
    - title: 'Bug Fixes'
      regexp: '^fix'
    - title: 'Performance Improvements'
      regexp: '^perf'
    - title: 'Breaking Changes'
      regexp: '^BREAKING CHANGE'
    - title: 'Other changes'

release:
  github:
    owner: toyamagu-2021
    name: k8s-manifest-diff
  prerelease: auto
  draft: false
  name_template: "{{.ProjectName}} v{{.Version}}"
  footer: |
    ## Installation

    Download the appropriate binary for your platform from the assets below.

    ### macOS/Linux
    ```bash
    # Download and extract (replace OS and ARCH)
    tar -xzf k8s-manifest-diff_<OS>_<ARCH>.tar.gz

    # Make executable
    chmod +x k8s-manifest-diff

    # Move to PATH (optional)
    sudo mv k8s-manifest-diff /usr/local/bin/
    ```

    ### Windows
    ```powershell
    # Extract the zip file and add to PATH
    ```
